### ISSUE TITLE
Move vendor and node_modules folders to persistent on servers to speed up deployments

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie-custom/blender#130]
Thoughts? @freekmurze

**Comment by freekmurze** [comment]
Pro: 
+ full deploys would indeed be a bit faster, (allthough it's pretty fast already with the node_modules and php packages being cached
+ backups would be performed faster, because there are less files to copy / deduplicate

Contra:
- while composer does it work updating requirements, the live site might go down
- symlinking to a previous is not guaranteed to work because required js / php dependencies might have changes

I'd leave it as it is for now.

**Comment by sebastiandedeyne** [comment]
Didn't consider the site going down during the update :(

Another reason why I wanted this was to reduce the CPU load, spikes they're pretty big.
