### ISSUE TITLE
Blender winter 2017 refresh

### ISSUE THREAD

**Issue by freekmurze** [spatie-custom/blender#143]
With Laravel 5.4 shipping in January, it's a good time to iterate on Blender again. We'll clear some time on the planning to perform these improvements:

- [x] Convert all views to make use of L5.4's slots
- [x] Ditch `php-enum`. we could make a trait to easily work with class constants and put that on classes that are 'owner' of the enum.
- [x] Rethink fragment workflow: make use of L5.4's json translations
- [x] Move `helpers.php` to `Services` to `Foundation` can be removed
- [x] Move factory definitions in Seeder classes so `database/factories` can be removed
- [x] Currently testing mails is a hassle. Let's add some artisan command with which mails with dummy content can be sent
- [x] Ditch `BladeDirectiveServiceProvider`
- [x] Rethink `HtmlBuilder` and `FormBuilder` (see #141)

All feedback / suggestions welcome.

**Comment by sebastiandedeyne** [comment]
Related packages:

- I might do a v2 of our html-element package in order to clean up `HtmlBuilder` and `FormBuilder`
- Clean up and improve the api of our seeders package

Re: `database/factories`, I don't want to remove the entire directory, just empty it be default and only use it for unit/integration test data (difference with seeds: seeds generate lots of data with Faker, factories would generate static data (which is easier to deal with in tests)
