### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by amosmos** [spatie-custom/blender#358]
Hi,

Can't tell you enough how awesome your work and packages are!

My question about blender is how do you keep it updated with each new release of Laravel, whether it's a big update like v5.3 to v5.4 but also the smaller ones in each big release? Do you merge the Laravel release into blender? Or maybe do it manually?

Thanks!

**Comment by sebastiandedeyne** [comment]
The smaller ones (patch releases like `5.3.1 => 5.3.2`) only need a `composer update` to pull in the latest version of the framework. Changes in [laravel/laravel](https://github.com/laravel/laravel) generally don't need immediate attention, since that repository is essentially a boilerplate.

For major versions, we've been happy [Laravel Shift](https://laravelshift.com/) customers lately (see #181 for the latest update). The trend seems to be that Laravel upgrades are becoming easier with the release though, so for `5.5` we might not even need to use Shift!

Hope that answers your question :)
