### ISSUE TITLE
Fresh Blender install throws an exception

### ISSUE THREAD

**Issue by AlexVanderbist** [spatie-custom/blender#388]
On a fresh Blender install any front page throws an exception for the following error: 
`Array to string conversion (View: blender/resources/views/front/_layouts/_partials/header.blade.php)`

**Comment by regal2157** [comment]
Recently tried to do a fresh install of this to check it out. I've had to modify a lot of files to get it working, so I feel there is something missing. Fixing one exception like this will just throw another.

A few of the translations seemed to have adopted another level, so for header.blade.php and register, etc, the lang 'auth.register' is now 'auth.register.submit' or 'auth.register.toLogin'

I've had other issues too where the action() calls need the full path: action('\App\Http\contollers\[Front,Back]\...') instead of just action('Front\...')

**Comment by sebastiandedeyne** [comment]
I think was fixed, or will be fixed when #452 is merged.
